repos:
    - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
      rev: v1.4.0
      hooks:
        - id: check-pre-commit-ci-config
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: check-yaml
        - id: check-merge-conflict
        - id: detect-private-key
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.1.0
      hooks:
        - id: add-trailing-comma
