orbs:
  ggshield: gitguardian/ggshield

workflows:
  main:
    jobs:
      - ggshield/scan:
          name: ggshield-scan # best practice is to name each orb jobs
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>
